import image from '../images/movie.png'

export const initialMovies = [
  {
    id: 1,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 2,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 3,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 4,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 5,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 6,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 7,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 8,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 9,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 10,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 11,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 12,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 13,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 14,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 15,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 16,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 17,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 18,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 19,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 20,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 21,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 22,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 23,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 24,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 25,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
];

export const savedMovies = [
  {
    id: 1,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 2,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
  {
    id: 3,
    image: image,
    nameRU: '33 слова о дизайне',
    duration: 47,
    trailerLink: 'https://youtu.be/__2oZSM1l1Q',
  },
];
